"""empty message

Revision ID: 48f171733666
Revises: d7cf0013e977
Create Date: 2022-03-09 17:23:45.548381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f171733666'
down_revision = 'd7cf0013e977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('issued_by', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issuances_id'), 'issuances', ['id'], unique=False)
    op.drop_table('tickets_to_users')
    op.add_column('domains', sa.Column('issuance_id', sa.Integer(), nullable=True))
    op.drop_constraint('domains_ticket_id_fkey', 'domains', type_='foreignkey')
    op.create_foreign_key(None, 'domains', 'issuances', ['issuance_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('domains', 'ticket_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.create_foreign_key('domains_ticket_id_fkey', 'domains', 'tickets', ['ticket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('domains', 'issuance_id')
    op.create_table('tickets_to_users',
    sa.Column('tickets_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tickets_id'], ['tickets.id'], name='tickets_to_users_tickets_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tickets_to_users_user_id_fkey')
    )
    op.drop_index(op.f('ix_issuances_id'), table_name='issuances')
    op.drop_table('issuances')
    # ### end Alembic commands ###
