"""empty message

Revision ID: ef395cf0e6b7
Revises: e987fa06cc7d
Create Date: 2022-03-06 04:27:11.599403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef395cf0e6b7'
down_revision = 'e987fa06cc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
