"""empty message

Revision ID: a846301a2ff5
Revises: f5c2d0e95538
Create Date: 2022-03-12 21:30:00.775765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a846301a2ff5'
down_revision = 'f5c2d0e95538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('domains_name_key', 'domains', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('domains_name_key', 'domains', ['name'])
    # ### end Alembic commands ###
