"""empty message

Revision ID: 386c67bdcfa7
Revises: abbef2df40b2
Create Date: 2022-03-24 16:01:54.294790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386c67bdcfa7'
down_revision = 'abbef2df40b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('result', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'result')
    # ### end Alembic commands ###
