"""empty message

Revision ID: 758f7839c148
Revises: a4e4d291095b
Create Date: 2022-03-06 09:15:47.349554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758f7839c148'
down_revision = 'a4e4d291095b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
