"""empty message

Revision ID: 381399aadabe
Revises: 15ba070baf9c
Create Date: 2022-07-31 07:08:25.874275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381399aadabe'
down_revision = '15ba070baf9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('domain_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'domain_uuid')
    # ### end Alembic commands ###
