"""empty message

Revision ID: a4e4d291095b
Revises: dd61ba0f1bf2
Create Date: 2022-03-06 09:15:41.204893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e4d291095b'
down_revision = 'dd61ba0f1bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks_portgroups',
    sa.Column('network_uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vlan_id', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('update_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_uuid'], ['networks.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('network_uuid', 'name')
    )
    op.drop_table('network_portgroups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_portgroups',
    sa.Column('network_uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('vlan_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['network_uuid'], ['networks.uuid'], name='network_portgroups_network_uuid_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('network_uuid', 'name', name='network_portgroups_pkey')
    )
    op.drop_table('networks_portgroups')
    # ### end Alembic commands ###
