"""empty message

Revision ID: 34144a1ec4e7
Revises: ef395cf0e6b7
Create Date: 2022-03-06 05:55:54.934761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34144a1ec4e7'
down_revision = 'ef395cf0e6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('vnc_port', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('vnc_password', sa.String(), nullable=True))
    op.add_column('domains_drives', sa.Column('device', sa.String(), nullable=True))
    op.add_column('domains_interfaces', sa.Column('bridge', sa.String(), nullable=True))
    op.add_column('domains_interfaces', sa.Column('port', sa.String(), nullable=True))
    op.drop_column('domains_interfaces', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains_interfaces', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('domains_interfaces', 'port')
    op.drop_column('domains_interfaces', 'bridge')
    op.drop_column('domains_drives', 'device')
    op.drop_column('domains', 'vnc_password')
    op.drop_column('domains', 'vnc_port')
    # ### end Alembic commands ###
