- hosts: node
  become: true
  gather_facts: no
  tasks:
  - name: ping connection
    ansible.builtin.ping:
  - name: stop agent
    service:
      name: virty-agent.service
      state: stopped
    failed_when: false
  - name: dir exists
    file:
      path: "/opt/virty/"
      state: directory
      owner: "root"
      group: "root"
      mode: "0755"
  - name: copy anget
    copy:
      src: ./main.bin
      dest: /opt/virty/agent
      owner: root
      group: root
      mode: '0744'
      backup: no
  - name: copy service
    copy:
      src: ./virty-agent.service
      dest: /lib/systemd/system/
      owner: root
      group: root
      mode: '0600'
      backup: no
  - name: restart virty-agent.service
    systemd:
      name: virty-agent.service
      state: restarted
      daemon_reload: yes
      enabled: yes
    become: yes