# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from virty_client.models.node_interface_ipv4_info import NodeInterfaceIpv4Info
from virty_client.models.node_interface_ipv6_info import NodeInterfaceIpv6Info
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NodeInterface(BaseModel):
    """
    NodeInterface
    """ # noqa: E501
    ifname: StrictStr
    operstate: StrictStr
    mtu: StrictInt
    master: Optional[StrictStr] = None
    link_type: StrictStr = Field(alias="linkType")
    mac_address: Optional[StrictStr] = Field(default=None, alias="macAddress")
    ipv4_info: List[NodeInterfaceIpv4Info] = Field(alias="ipv4Info")
    ipv6_info: List[NodeInterfaceIpv6Info] = Field(alias="ipv6Info")
    __properties: ClassVar[List[str]] = ["ifname", "operstate", "mtu", "master", "linkType", "macAddress", "ipv4Info", "ipv6Info"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NodeInterface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ipv4_info (list)
        _items = []
        if self.ipv4_info:
            for _item in self.ipv4_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ipv4Info'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ipv6_info (list)
        _items = []
        if self.ipv6_info:
            for _item in self.ipv6_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ipv6Info'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NodeInterface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ifname": obj.get("ifname"),
            "operstate": obj.get("operstate"),
            "mtu": obj.get("mtu"),
            "master": obj.get("master"),
            "linkType": obj.get("linkType"),
            "macAddress": obj.get("macAddress"),
            "ipv4Info": [NodeInterfaceIpv4Info.from_dict(_item) for _item in obj.get("ipv4Info")] if obj.get("ipv4Info") is not None else None,
            "ipv6Info": [NodeInterfaceIpv6Info.from_dict(_item) for _item in obj.get("ipv6Info")] if obj.get("ipv6Info") is not None else None
        })
        return _obj


