version: "3"
services:
  virty-main:
    build: ./main
    volumes:
      - ./data/app:/opt/virty/app/data/
      - ./data/key:/root/.ssh/
    environment:
      VIRTY_ROOT: "/opt/virty/app/"
    restart: always
  virty-web:
    build: ./web
    volumes:
      - ./data/nginx:/var/log/nginx/
    ports:
      - 0.0.0.0:80:80
    restart: always