version: "3"
services:
  virty-main:
    build: ./docker/virty-main
    volumes:
      - ./key:/root/.ssh
      - ./main:/root/virty/main
      - ./docker/volume/uwsgi_log:/var/log/uwsgi/
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - virty_backend

  virty-main:
    build: ./docker/virty-nginx
    volumes:
      - ./docker/volume/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/volume/nginx_log:/var/log/nginx/
    ports:
      - "50081:80"
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - vhosts
      - virty_backend

networks:
  vhosts:
    external: true
  virty_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default