version: "3"
services:
  main:
    build: ./docker/virty-main
    volumes:
      - ./key:/root/.ssh
      - ./main:/root/virty/main
      - ./docker/volume/uwsgi_log:/var/log/uwsgi/
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    restart: always

  nginx:
    build: ./docker/virty-nginx
    volumes:
      - ./docker/volume/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/volume/nginx_log:/var/log/nginx/
    links:
      - main
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    restart: always