version: "3"
services:
  virty-main:
    # tty: true
    build: ./main
    volumes:
      - ./key:/root/.ssh
      - ./main:/root/virty/main
      - ./log/main:/var/log/uwsgi/
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - virty_backend

  virty-web:
    build: ./web
    volumes:
      - ./log/nginx:/var/log/nginx/
    ports:
      - "50081:80"
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - vhosts
      - virty_backend

networks:
  vhosts:
    external: true
  virty_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default