version: "3"
services:
  api:
    build: ./api
    volumes:
      - api-data:/opt/data
      - api-key:/root/.ssh/
    environment:
      APP_ROOT: "/opt/app"
      DATA_ROOT: "/opt/data"
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    restart: always
  worker:
    build: ./api
    volumes:
      - api-data:/opt/data
      - api-key:/root/.ssh/
    environment:
      APP_ROOT: "/opt/app"
      DATA_ROOT: "/opt/data"
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    restart: always
    command: python3 /opt/app/worker.py
  nginx:
    build: ./nginx
    ports: 0.0.0.0:8765:80
    restart: always
  next:
    build: ./next
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: ""
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
    restart: unless-stopped
  proxy:
    build: ./proxy
    restart: always
    command: websockify --verbose --web /usr/share/novnc/ --token-plugin JSONTokenApi --token-source "http://api:8000/api/vms/vnc/%s" 5999

volumes:
  postgres-data:
  api-data:
  api-key: