version: "3"
services:
  main:
    build: ./main
    volumes:
      - ./data/data:/opt/data
      - ./data/key:/root/.ssh/
    environment:
      APP_ROOT: "/opt/app"
      DATA_ROOT: "/opt/data"
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    restart: always
  web:
    build: ./web
    volumes:
      - ./data/nginx:/var/log/nginx/
    ports:
      - 0.0.0.0:80:80
    restart: always
  db:
    image: postgres:latest
    volumes:
      - virty-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
    restart: unless-stopped

volumes:
  virty-postgres-data: