version: "3"
services:
  api:
    build: ./api
    hostname: virty-api
    volumes:
      - ./data/app:/opt/data
      - ./data/key:/root/.ssh/
    environment:
      APP_ROOT: "/opt/app"
      DATA_ROOT: "/opt/data"
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:password@virty-db:5432/mydatabase"
    restart: always
  web:
    hostname: virty-web
    build: ./web
    volumes:
      - ./data/nginx:/var/log/nginx/
    ports:
      - 0.0.0.0:8765:80
    restart: always
  db:
    hostname: virty-db
    image: postgres:latest
    volumes:
      - virty-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
    restart: unless-stopped

volumes:
  virty-postgres-data: