site_name: Vrity Document
copyright: "&copy; 2019-2025 hibiki31"

theme:
  name: material
  language: 'ja'
  palette:
    primary: teal
  font:
    text: Noto Sans JP
    code: Roboto Mono
repo_url: https://github.com/hibiki31/virty
repo_name: hibiki31/virty
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
extra:
  alternate:
    - name: Japanese
      link: /
      lang: ja
  generator: false
  search:
    language: 'jp'
