- hosts: all
  become: yes
  tasks:
    - block:
      - name: apt update
        apt:
          update_cache: yes
  
      - name: Install libvirt qemu
        apt:
          name: "{{ packages }}"
        vars:
          packages: 
            # - qemu
            - qemu-kvm
            - qemu-utils
            - libvirt-daemon
            - libvirt-clients
            - libvirt-dev
            - bridge-utils
            - virt-manager
            - rsync

      - name: restart libvirtd
        systemd:
          name: libvirtd
          state: restarted
          daemon_reload: yes
          enabled: yes
      when: ansible_distribution == "Ubuntu"