- hosts: all
  gather_facts: True
  tasks:
  - name: check connection
    ping:
  - name: setup
    setup:
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts 
                state=present
                dest=/etc/hosts 
                regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" 
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "{{ groups['all'] }}"