/*
VirtyAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UserProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProject{}

// UserProject struct for UserProject
type UserProject struct {
	Name string `json:"name"`
}

type _UserProject UserProject

// NewUserProject instantiates a new UserProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProject(name string) *UserProject {
	this := UserProject{}
	this.Name = name
	return &this
}

// NewUserProjectWithDefaults instantiates a new UserProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProjectWithDefaults() *UserProject {
	this := UserProject{}
	return &this
}

// GetName returns the Name field value
func (o *UserProject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserProject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserProject) SetName(v string) {
	o.Name = v
}

func (o UserProject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UserProject) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserProject := _UserProject{}

	err = json.Unmarshal(bytes, &varUserProject)

	if err != nil {
		return err
	}

	*o = UserProject(varUserProject)

	return err
}

type NullableUserProject struct {
	value *UserProject
	isSet bool
}

func (v NullableUserProject) Get() *UserProject {
	return v.value
}

func (v *NullableUserProject) Set(val *UserProject) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProject) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProject(val *UserProject) *NullableUserProject {
	return &NullableUserProject{value: val, isSet: true}
}

func (v NullableUserProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


