/*
VirtyAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the NetworkForUpdateDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkForUpdateDomain{}

// NetworkForUpdateDomain struct for NetworkForUpdateDomain
type NetworkForUpdateDomain struct {
	Mac string `json:"mac"`
	NetworkUuid string `json:"networkUuid"`
	Port *string `json:"port,omitempty"`
}

type _NetworkForUpdateDomain NetworkForUpdateDomain

// NewNetworkForUpdateDomain instantiates a new NetworkForUpdateDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkForUpdateDomain(mac string, networkUuid string) *NetworkForUpdateDomain {
	this := NetworkForUpdateDomain{}
	this.Mac = mac
	this.NetworkUuid = networkUuid
	return &this
}

// NewNetworkForUpdateDomainWithDefaults instantiates a new NetworkForUpdateDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkForUpdateDomainWithDefaults() *NetworkForUpdateDomain {
	this := NetworkForUpdateDomain{}
	return &this
}

// GetMac returns the Mac field value
func (o *NetworkForUpdateDomain) GetMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mac
}

// GetMacOk returns a tuple with the Mac field value
// and a boolean to check if the value has been set.
func (o *NetworkForUpdateDomain) GetMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mac, true
}

// SetMac sets field value
func (o *NetworkForUpdateDomain) SetMac(v string) {
	o.Mac = v
}

// GetNetworkUuid returns the NetworkUuid field value
func (o *NetworkForUpdateDomain) GetNetworkUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkUuid
}

// GetNetworkUuidOk returns a tuple with the NetworkUuid field value
// and a boolean to check if the value has been set.
func (o *NetworkForUpdateDomain) GetNetworkUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkUuid, true
}

// SetNetworkUuid sets field value
func (o *NetworkForUpdateDomain) SetNetworkUuid(v string) {
	o.NetworkUuid = v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *NetworkForUpdateDomain) GetPort() string {
	if o == nil || IsNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkForUpdateDomain) GetPortOk() (*string, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *NetworkForUpdateDomain) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *NetworkForUpdateDomain) SetPort(v string) {
	o.Port = &v
}

func (o NetworkForUpdateDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkForUpdateDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mac"] = o.Mac
	toSerialize["networkUuid"] = o.NetworkUuid
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	return toSerialize, nil
}

func (o *NetworkForUpdateDomain) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mac",
		"networkUuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkForUpdateDomain := _NetworkForUpdateDomain{}

	err = json.Unmarshal(bytes, &varNetworkForUpdateDomain)

	if err != nil {
		return err
	}

	*o = NetworkForUpdateDomain(varNetworkForUpdateDomain)

	return err
}

type NullableNetworkForUpdateDomain struct {
	value *NetworkForUpdateDomain
	isSet bool
}

func (v NullableNetworkForUpdateDomain) Get() *NetworkForUpdateDomain {
	return v.value
}

func (v *NullableNetworkForUpdateDomain) Set(val *NetworkForUpdateDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkForUpdateDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkForUpdateDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkForUpdateDomain(val *NetworkForUpdateDomain) *NullableNetworkForUpdateDomain {
	return &NullableNetworkForUpdateDomain{value: val, isSet: true}
}

func (v NullableNetworkForUpdateDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkForUpdateDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


