/*
VirtyAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CdromForUpdateDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdromForUpdateDomain{}

// CdromForUpdateDomain struct for CdromForUpdateDomain
type CdromForUpdateDomain struct {
	Path *string `json:"path,omitempty"`
	Target *string `json:"target,omitempty"`
}

// NewCdromForUpdateDomain instantiates a new CdromForUpdateDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdromForUpdateDomain() *CdromForUpdateDomain {
	this := CdromForUpdateDomain{}
	return &this
}

// NewCdromForUpdateDomainWithDefaults instantiates a new CdromForUpdateDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdromForUpdateDomainWithDefaults() *CdromForUpdateDomain {
	this := CdromForUpdateDomain{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *CdromForUpdateDomain) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdromForUpdateDomain) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *CdromForUpdateDomain) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *CdromForUpdateDomain) SetPath(v string) {
	o.Path = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *CdromForUpdateDomain) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdromForUpdateDomain) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *CdromForUpdateDomain) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *CdromForUpdateDomain) SetTarget(v string) {
	o.Target = &v
}

func (o CdromForUpdateDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdromForUpdateDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	return toSerialize, nil
}

type NullableCdromForUpdateDomain struct {
	value *CdromForUpdateDomain
	isSet bool
}

func (v NullableCdromForUpdateDomain) Get() *CdromForUpdateDomain {
	return v.value
}

func (v *NullableCdromForUpdateDomain) Set(val *CdromForUpdateDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableCdromForUpdateDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableCdromForUpdateDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdromForUpdateDomain(val *CdromForUpdateDomain) *NullableCdromForUpdateDomain {
	return &NullableCdromForUpdateDomain{value: val, isSet: true}
}

func (v NullableCdromForUpdateDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdromForUpdateDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


