/*
VirtyAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the Flavor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Flavor{}

// Flavor struct for Flavor
type Flavor struct {
	Count int32 `json:"count"`
	Data []FlavorPage `json:"data"`
}

type _Flavor Flavor

// NewFlavor instantiates a new Flavor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlavor(count int32, data []FlavorPage) *Flavor {
	this := Flavor{}
	this.Count = count
	this.Data = data
	return &this
}

// NewFlavorWithDefaults instantiates a new Flavor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlavorWithDefaults() *Flavor {
	this := Flavor{}
	return &this
}

// GetCount returns the Count field value
func (o *Flavor) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *Flavor) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *Flavor) SetCount(v int32) {
	o.Count = v
}

// GetData returns the Data field value
func (o *Flavor) GetData() []FlavorPage {
	if o == nil {
		var ret []FlavorPage
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Flavor) GetDataOk() ([]FlavorPage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *Flavor) SetData(v []FlavorPage) {
	o.Data = v
}

func (o Flavor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Flavor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *Flavor) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlavor := _Flavor{}

	err = json.Unmarshal(bytes, &varFlavor)

	if err != nil {
		return err
	}

	*o = Flavor(varFlavor)

	return err
}

type NullableFlavor struct {
	value *Flavor
	isSet bool
}

func (v NullableFlavor) Get() *Flavor {
	return v.value
}

func (v *NullableFlavor) Set(val *Flavor) {
	v.value = val
	v.isSet = true
}

func (v NullableFlavor) IsSet() bool {
	return v.isSet
}

func (v *NullableFlavor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlavor(val *Flavor) *NullableFlavor {
	return &NullableFlavor{value: val, isSet: true}
}

func (v NullableFlavor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlavor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


