/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/images/': RouteRecordInfo<'/images/', '/images', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/networks/': RouteRecordInfo<'/networks/', '/networks', Record<never, never>, Record<never, never>>,
    '/nodes/': RouteRecordInfo<'/nodes/', '/nodes', Record<never, never>, Record<never, never>>,
    '/nodes/[name]': RouteRecordInfo<'/nodes/[name]', '/nodes/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/storages/': RouteRecordInfo<'/storages/', '/storages', Record<never, never>, Record<never, never>>,
    '/tasks/': RouteRecordInfo<'/tasks/', '/tasks', Record<never, never>, Record<never, never>>,
    '/vms/': RouteRecordInfo<'/vms/', '/vms', Record<never, never>, Record<never, never>>,
    '/vms/[uuid]': RouteRecordInfo<'/vms/[uuid]', '/vms/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
  }
}
