FROM python:3.12-bullseye

WORKDIR /tmp

COPY ../requirements.txt ../requirements.dev.txt ./

RUN python3 -m pip install --upgrade pip \
 && pip3 install --user -r ./requirements.txt \
 && pip3 install --user -r ./requirements.dev.txt

ENV PATH $PATH:/root/.local/bin/

EXPOSE 8000