FROM node:16-buster as build-stage

WORKDIR /app
COPY . .

RUN yarn install
RUN yarn build-storybook


FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/storybook-static /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]