version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile.dev
    ports:
      - 0.0.0.0:8765:8765
    volumes:
      - "../../:/workspaces:cached"
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - virty-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password

volumes:
  virty-postgres-data: