- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: cp img
      copy: 
        src: '{{ src }}' 
        dest: '{{ dst }}'
        owner: root
        group: root
        mode: 0644
        remote_src: yes