# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.metrics_api import MetricsApi


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsApi()

    def tearDown(self) -> None:
        pass

    def test_get_metrics(self) -> None:
        """Test case for get_metrics

        Exporter Get
        """
        pass


if __name__ == '__main__':
    unittest.main()
