# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.networks_task_api import NetworksTaskApi


class TestNetworksTaskApi(unittest.TestCase):
    """NetworksTaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworksTaskApi()

    def tearDown(self) -> None:
        pass

    def test_create_network(self) -> None:
        """Test case for create_network

        Post Api Storage
        """
        pass

    def test_create_network_ovs(self) -> None:
        """Test case for create_network_ovs

        Post Uuid Ovs
        """
        pass

    def test_delete_network(self) -> None:
        """Test case for delete_network

        Delete Api Storage
        """
        pass

    def test_delete_network_ovs(self) -> None:
        """Test case for delete_network_ovs

        Post Api Networks Uuid Ovs
        """
        pass

    def test_post_uuid_ovs_api_tasks_networks_providers_post(self) -> None:
        """Test case for post_uuid_ovs_api_tasks_networks_providers_post

        Post Uuid Ovs
        """
        pass

    def test_refresh_networks(self) -> None:
        """Test case for refresh_networks

        Put Api Networks
        """
        pass


if __name__ == '__main__':
    unittest.main()
