# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.nodes_task_api import NodesTaskApi


class TestNodesTaskApi(unittest.TestCase):
    """NodesTaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodesTaskApi()

    def tearDown(self) -> None:
        pass

    def test_create_node(self) -> None:
        """Test case for create_node

        Post Tasks Nodes
        """
        pass

    def test_delete_node(self) -> None:
        """Test case for delete_node

        Delete Tasks Nodes Name
        """
        pass

    def test_update_node_role(self) -> None:
        """Test case for update_node_role

        Patch Api Node Role
        """
        pass


if __name__ == '__main__':
    unittest.main()
