# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.storages_api import StoragesApi


class TestStoragesApi(unittest.TestCase):
    """StoragesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StoragesApi()

    def tearDown(self) -> None:
        pass

    def test_create_storage_pool(self) -> None:
        """Test case for create_storage_pool

        Post Api Storages Pools
        """
        pass

    def test_get_storage(self) -> None:
        """Test case for get_storage

        Get Api Storages Uuid
        """
        pass

    def test_get_storage_pools(self) -> None:
        """Test case for get_storage_pools

        Get Api Storages Pools
        """
        pass

    def test_get_storages(self) -> None:
        """Test case for get_storages

        Get Api Storages
        """
        pass

    def test_update_storage_metadata(self) -> None:
        """Test case for update_storage_metadata

        Post Api Storage
        """
        pass

    def test_update_storage_pool(self) -> None:
        """Test case for update_storage_pool

        Post Api Storages Pools
        """
        pass


if __name__ == '__main__':
    unittest.main()
