# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_create_project(self) -> None:
        """Test case for create_project

        Post Api Projects
        """
        pass

    def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete Api Projects
        """
        pass

    def test_get_projects(self) -> None:
        """Test case for get_projects

        Get Api Projects
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Put Api Projects
        """
        pass


if __name__ == '__main__':
    unittest.main()
