# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.storages_task_api import StoragesTaskApi


class TestStoragesTaskApi(unittest.TestCase):
    """StoragesTaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StoragesTaskApi()

    def tearDown(self) -> None:
        pass

    def test_create_storage(self) -> None:
        """Test case for create_storage

        Post Api Storage
        """
        pass

    def test_delete_storage(self) -> None:
        """Test case for delete_storage

        Delete Api Storages
        """
        pass


if __name__ == '__main__':
    unittest.main()
