# coding: utf-8

"""
    VirtyAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 4.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from virty_client.api.flavors_api import FlavorsApi


class TestFlavorsApi(unittest.TestCase):
    """FlavorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlavorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_flavor(self) -> None:
        """Test case for create_flavor

        Post Api Flavors
        """
        pass

    def test_delete_flavor(self) -> None:
        """Test case for delete_flavor

        Delete Flavors
        """
        pass

    def test_get_flavors(self) -> None:
        """Test case for get_flavors

        Get Api Flavors
        """
        pass


if __name__ == '__main__':
    unittest.main()
