services:
  app:
    build: ../
    ports:
      - 0.0.0.0:7799:7799
    volumes:
      - "../../:/workspaces:cached"
      - virty-develop-ssh-key:/root/.ssh
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - virty-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password

volumes:
  virty-postgres-data:
  virty-develop-ssh-key: