version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - "../../:/workspace:cached"
      - virty-develop-ssh-key:/root/.ssh
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - virty-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password

volumes:
  virty-postgres-data:
  virty-develop-ssh-key: