[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# ALL
select = [
    "E",
    "F"
]
ignore = [
    "D100", # パブリックモジュールにはdocstringを書く必要がある
    "INP001", # __init__.pyでモジュールを初期化する必要がある
    "E501", #文字数!!!!
]
fixable = ["ALL"]
target-version = "py39"

# Exclude a variety of commonly ignored directories.
exclude = [".venv", "venv"]