name: Docker build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build test vue
        uses: docker/build-push-action@v6
        with:
          context: ./vue
          push: false
          cache-from: type=gha
          cache-to: type=gha

      - name: Build test api
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: false
          cache-from: type=gha
          cache-to: type=gha